name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

env:  
  # The RESOURCE_PREFIX is now read from a repository variable for environment-specific deployments.
  RESOURCE_PREFIX: ${{ vars.RESOURCE_PREFIX }}

jobs:
  build_and_deploy:
4    runs-on: ubuntu-latest
    steps:
      - name: ðŸ§¹ Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Foundational Resources (Stage 1)
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_PREFIX }}-rg
          template: ./deploy/main.bicep
          parameters: >
            resourcePrefix=${{ env.RESOURCE_PREFIX }}
            ragAppUsername=${{ secrets.RAG_APP_USERNAME }}
            ragAppPassword=${{ secrets.RAG_APP_PASSWORD }}
            deployApps=false
          scope: resourcegroup
          deploymentName: gh-workflow-foundational-${{ github.run_id }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.RESOURCE_PREFIX }}acr.azurecr.io

      - name: ðŸ•µï¸ List files in build context
        run: |
          echo "Listing all files and directories..."
          ls -la

      - name: Build and push rag-app container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.RESOURCE_PREFIX }}acr.azurecr.io/rag-app:${{ github.sha }}

      - name: Build and push ollama-app container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ollama
          push: true
          tags: ${{ env.RESOURCE_PREFIX }}acr.azurecr.io/rag-app-ollama:${{ github.sha }}

      - name: Deploy Application Services (Stage 2)
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_PREFIX }}-rg
          template: ./deploy/main.bicep
          parameters: >
            resourcePrefix=${{ env.RESOURCE_PREFIX }}
            ragAppUsername=${{ secrets.RAG_APP_USERNAME }}
            ragAppPassword=${{ secrets.RAG_APP_PASSWORD }}
            deployApps=true
          scope: resourcegroup
          deploymentName: gh-workflow-deployment-${{ github.run_id }}
