# Use the official Ollama base image
FROM ollama/ollama

# Update underlying OS packages to patch known security vulnerabilities.
# This is a best practice for hardening Docker images.
RUN apt-get update && apt-get upgrade -y --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Copy the entrypoint script and set it to run on container start
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]